### ISSUE TITLE
LiveTV from abroad raises StopIteration exception

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#130]
### Describe the bug ###
Starting LiveTV using addon v1.7.1 from NL returns in the below log output:
```
2019-04-14 00:01:18.466 T:53120  NOTICE: [plugin.video.vrt.nu] video_url https://www.vrt.be/vrtnu/kanalen/een/
2019-04-14 00:01:18.815 T:53120  NOTICE: [plugin.video.vrt.nu] Cached token deleted
2019-04-14 00:01:19.378 T:53120  NOTICE: [plugin.video.vrt.nu] Invalid location; required BE
2019-04-14 00:01:20.629 T:53120   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.StopIteration'>
                                            Traceback (most recent call last):
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\addon.py", line 58, in <module>
                                                router(sys.argv[2][1:])
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\addon.py", line 52, in router
                                                vrt_player.play(video)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\vrtplayer\vrtplayer.py", line 65, in play
                                                stream = self._stream_service.get_stream(video)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\vrtplayer\streamservice.py", line 136, in get_stream
                                                roaming_xvrttoken = self.token_resolver.get_xvrttoken(True)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\vrtplayer\tokenresolver.py", line 54, in get_xvrttoken
                                                token = self._get_new_xvrttoken(token_path, get_roaming_token)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\vrtplayer\tokenresolver.py", line 101, in _get_new_xvrttoken
                                                xvrttoken = self._get_roaming_xvrttoken(login_cookie, xvrttoken)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\vrtplayer\tokenresolver.py", line 122, in _get_roaming_xvrttoken
                                                roaming_xvrttoken = TokenResolver._create_token_dictionary(cookie_jar)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\vrtplayer\tokenresolver.py", line 128, in _create_token_dictionary
                                                xvrttoken_cookie = next(TokenResolver.get_xvrttoken_from_cookiejar(cookie_jar))
                                            StopIteration
                                            -->End of Python script error report<--
```

### To Reproduce ###
1. Go to LiveTV and select Eén.
2. Get Kodi Addon error popup

### Expected behavior ###
A proper message that LiveTV is no supported from outside of BE.

### Additional context ###

- Operating system: Windows 10
- Kodi version: v18.0
- Addon version: v1.7.1
- Using a VPN: no
- Country you are using the addon from: NL

### Log (if available) ###
```paste below
2019-04-14 00:01:18.466 T:53120  NOTICE: [plugin.video.vrt.nu] video_url https://www.vrt.be/vrtnu/kanalen/een/
2019-04-14 00:01:18.815 T:53120  NOTICE: [plugin.video.vrt.nu] Cached token deleted
2019-04-14 00:01:19.378 T:53120  NOTICE: [plugin.video.vrt.nu] Invalid location; required BE
2019-04-14 00:01:20.629 T:53120   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.StopIteration'>
                                            Traceback (most recent call last):
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\addon.py", line 58, in <module>
                                                router(sys.argv[2][1:])
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\addon.py", line 52, in router
                                                vrt_player.play(video)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\vrtplayer\vrtplayer.py", line 65, in play
                                                stream = self._stream_service.get_stream(video)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\vrtplayer\streamservice.py", line 136, in get_stream
                                                roaming_xvrttoken = self.token_resolver.get_xvrttoken(True)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\vrtplayer\tokenresolver.py", line 54, in get_xvrttoken
                                                token = self._get_new_xvrttoken(token_path, get_roaming_token)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\vrtplayer\tokenresolver.py", line 101, in _get_new_xvrttoken
                                                xvrttoken = self._get_roaming_xvrttoken(login_cookie, xvrttoken)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\vrtplayer\tokenresolver.py", line 122, in _get_roaming_xvrttoken
                                                roaming_xvrttoken = TokenResolver._create_token_dictionary(cookie_jar)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\vrtplayer\tokenresolver.py", line 128, in _create_token_dictionary
                                                xvrttoken_cookie = next(TokenResolver.get_xvrttoken_from_cookiejar(cookie_jar))
                                            StopIteration
                                            -->End of Python script error report<-
```

**Comment by dagwieers** [comment]
A nice alternative is to disable/gray-out the LiveTV menu item when abroad (requires detection first).

One possibility is to have a caching mechanism that remembers this specific error and keeps the menu-item greyed-out until the next restart of the add-on. (i.e. have a *global* boolean default to True, but on error, turn it into False, and a relation in the menuitem with this boolean).

We should also flag the Live TV channels ad Geo-blocked by default.

**Comment by michaelarnauts** [comment]
Caching may get be issues when you are abroad, and forget to connect to a VPN. You then need a way to kill the add-on for it to try again .

**Comment by dagwieers** [comment]
Exiting and starting another addon would suffice, or an entry in the settings to reset.

**Comment by mediaminister** [comment]
Normally all video works in the European Union if you validated a Belgian mobile phone number in your VRT-account. But VRT changed something that broke `_get_roaming_xvrttoken`. I fixed it: https://github.com/pietje666/plugin.video.vrt.nu/pull/132

**Comment by dagwieers** [comment]
@mediaminister Should we then improve the geo-locked statement to indicate if it is BE or EU?
Or is it *always* EU when geo-locked?

**Comment by mediaminister** [comment]
VRT api `allowedRegion` key has two possible values: `WORLD` and `BE`
So, BE means EU for people with a validated Belgian mobile phone number.

**Comment by dagwieers** [comment]
@mediaminister Ok, so I'll keep it as-is. But it still means the Live TV streams are geo-locked as well.

**Comment by mediaminister** [comment]
Indeed, but livestream info is not available trough the api. We can assume that restrictions for the livestream are the strictest cause all programs can be viewed via the livestream:
- geolocked to BE/EU
- protected from copying by DRM
