### ISSUE TITLE
plugin stopped working on arm64 kszaq LE Kodi

### ISSUE THREAD

**Issue by NofanTasi** [pietje666/plugin.video.vrt.nu#14]
```
22:42:22.350 T:546266149088   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'simplejson.scanner.JSONDecodeError'>
                                            Error Contents: Expecting value: line 2 column 1 (char 1)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/addon.py", line 37, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/addon.py", line 30, in router
                                                kodi_wrapper.play_video(params['video'])
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py", li
ne 42, in play_video
                                                stream = stream_service.get_stream_from_url(path)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py"
, line 49, in get_stream_from_url
                                                json = securevideo_response.json()
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 850, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/usr/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
                                              File "/usr/lib/python2.7/site-packages/simplejson/scanner.py", line 127, in scan_once
                                              File "/usr/lib/python2.7/site-packages/simplejson/scanner.py", line 118, in _scan_once
                                            JSONDecodeError: Expecting value: line 2 column 1 (char 1)
                                            -->End of Python script error report<--
22:42:22.600 T:547861798912   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vrt.nu/?action=play&video=%2F
vrtnu%2Fa-z%2Fde-afspraak%2F2017%2Fde-afspraak-d20170928%2F]

```

**Comment by pietje666** [comment]
It seems the way vrt.nu was working before has changed alot. I will have to rebuild the way how to get the .M3u8 streams. My first glance on it was that they use a new service. Before i can use that i will have to ask acces since they have some License info:

License

U erkent uitdrukkelijk dat de informatie en gegevens verstrekt via services.vrt.be eigendom zijn en blijven van de VRT.
Het gebruik ervan is dan ook enkel bestemd voor de websites en andere toepassingen van VRT.
Voor gebruik van voormelde diensten, gegevens en/of informatie, op welke manier dan ook en ongeacht voor welke doeleinden, vraagt u de uitdrukkelijke, voorafgaande en schriftelijke toestemming van VRT via de VRT klantendienst.
Ingeval van onrechtmatig gebruik van deze gegevens, behoudt VRT zich het recht voor om alle maatregelen die nodig zijn om haar rechten te vrijwaren.
