### ISSUE TITLE
Cannot load any listing in Categories, A-Z or Recent

### ISSUE THREAD

**Issue by subutux** [pietje666/plugin.video.vrt.nu#146]
### Describe the bug ###

When requesting to list the categories, A-Z or Recent, the script fails to show the listing.

### To Reproduce ###
1. Go to Categories
2. Wait
3. Error is shown

### Expected behavior ###

Getting a list of categories

### Additional context ###
After some debugging, this seems to be related to https://github.com/urllib3/urllib3/issues/1585, urllib3 1.25.1 parse_url no longer accepts urls containing "[" and "]" as valid urls.

They're suggesting to precent encode those characters. haven't tested that yet, but shoud work.

- Operating system: OSMC
- Kodi version: 1.18
- Addon version: 1.7.1
- Using a VPN: no
- Country you are using the addon from: Belgium 🇧🇪

### Log (if available) ###
Stacktrace
```paste below
2019-04-26 20:18:39.605 T:916452064   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.InvalidURL'>
                                            Error Contents: Failed to parse: https://vrtnu-api.vrt.be/suggest?facets[categories]=met-audiodescriptie
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/addon.py", line 58, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/addon.py", line 45, in router
                                                vrt_player.show_tvshow_menu_items(params.get('video_url'))
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py", line 56, in show_tvshow_menu_items
                                                tvshow_items = self._api_helper.get_tvshow_items(path)
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py", line 31, in get_tvshow_items
                                                tvshows_req = requests.get(api_url, proxies=self._proxies)
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 519, in request
                                                prep = self.prepare_request(req)
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 462, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 313, in prepare
                                                self.prepare_url(url, params)
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 381, in prepare_url
                                                raise InvalidURL(*e.args)
                                            InvalidURL: Failed to parse: https://vrtnu-api.vrt.be/suggest?facets[categories]=met-audiodescriptie
                                            -->End of Python script error report<--
2019-04-26 20:18:40.184 T:882881248   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/?action=listingcategorytvshows&video_url=met-audiodescriptie
2019-04-26 20:18:40.199 T:1915741744   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/?action=listingcategorytvshows&video_url=met-audiodescriptie) failed


```

**Comment by JeanPoll** [comment]
I have the same issue

**Comment by dagwieers** [comment]
You can get the quickfix from the master branch by following these instructions: https://github.com/pietje666/plugin.video.vrt.nu/wiki/Updating#running-the-latest-development-tree-master-branch

PS And enjoy the new integrated TV guide, feedback welcome.

**Comment by dagwieers** [comment]
We just release v1.8.0 which will become available as soon as it is accepted upstream.
You can download it using these instructions: https://github.com/pietje666/plugin.video.vrt.nu/wiki/Updating#manual-updating

PS And enjoy the new integrated TV guide, feedback welcome.

**Comment by dagwieers** [comment]
The upstream bug in urllib3 is also fixed in the meantime:
- https://github.com/Freso/script.module.urllib3/issues/2
- https://github.com/urllib3/urllib3/issues/1585
