### ISSUE TITLE
Problem playing streams including livestreams

### ISSUE THREAD

**Issue by wvanlammeren** [pietje666/plugin.video.vrt.nu#30]
Currently running 1.4.0 on an updated osmc.

I checked the logs and see the following error:
```
19:48:37.701 T:1353708288   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'text'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/addon.py", line 43, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/addon.py", line 32, in router
                                                vrt_player.show_videos(params['video'])
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py", line 116, in show_videos
                                                episode_items = self.__get_episodes(li_tags)
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py", line 137, in __get_episodes
                                                title = statichelper.replace_newlines_and_strip(a_tag.text)
                                            AttributeError: 'NoneType' object has no attribute 'text'
                                            -->End of Python script error report<--
```

I have the suspicion that this occurs when trying to display more than one 'stream' in a folder. 
Displaying subfolders for seasons doesn't result in an error.
Also displaying folders with only 1 stream in them (like most movies and some docu's), also is no problem.

Livestreams have a different error message:
```
19:57:14.368 T:1926318592    INFO: easy_aquire - Created session to https://live-vrt.akamaized.net
19:57:14.401 T:1362096896    INFO: Python script stopped
19:57:14.402 T:1362096896   DEBUG: Thread LanguageInvoker 1362096896 terminating
19:57:20.139 T:1926318592   DEBUG: CCurlFile::GetMimeType - https://live-vrt.akamaized.net/groupc/live/***replaced***/live_aes.isml/.m3u8 -> application/x-mpegURL
19:57:20.173 T:1926318592   DEBUG: Loading settings for https://live-vrt.akamaized.net/groupc/live/***replaced***/live_aes.isml/.m3u8
19:57:20.189 T:1926318592   DEBUG: CPlayerCoreFactory::GetPlayers(https://live-vrt.akamaized.net/groupc/live/***replaced***/live_aes.isml/.m3u8)
19:57:20.190 T:1926318592   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: system rules
19:57:20.190 T:1926318592   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: system rules
19:57:20.190 T:1926318592   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mms/udp
19:57:20.190 T:1926318592   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
19:57:20.190 T:1926318592   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
19:57:20.191 T:1926318592   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
19:57:20.191 T:1926318592   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: streams
19:57:20.191 T:1926318592   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: streams
19:57:20.191 T:1926318592   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: aacp/sdp
19:57:20.191 T:1926318592   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mp2
19:57:20.191 T:1926318592   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvd
19:57:20.191 T:1926318592   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvdimage
19:57:20.191 T:1926318592   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
19:57:20.191 T:1926318592   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: nsv
19:57:20.191 T:1926318592   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: radio
19:57:20.192 T:1926318592   DEBUG: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
19:57:20.192 T:1926318592   DEBUG: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (VideoPlayer)
19:57:20.192 T:1926318592   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=0
19:57:20.192 T:1926318592   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
19:57:20.192 T:1926318592   DEBUG: CPlayerCoreFactory::GetPlayers: added 1 players
19:57:20.199 T:1926318592   DEBUG: Radio UECP (RDS) Processor - new CDVDRadioRDSData
19:57:20.199 T:1926318592  NOTICE: VideoPlayer: Opening: https://live-vrt.akamaized.net/groupc/live/***replaced***/live_aes.isml/.m3u8
19:57:20.199 T:1926318592 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
19:57:20.219 T:1926318592   DEBUG: CCurlFile::GetMimeType - https://live-vrt.akamaized.net/groupc/live/***replaced***/live_aes.isml/.m3u8 -> application/x-mpegURL
19:57:20.219 T:1926318592   DEBUG: CMMALRenderer::CMMALRenderer
19:57:20.219 T:1926318592   DEBUG: CMMALRenderer::UnInitMMAL
19:57:20.219 T:1353708288   DEBUG: Thread MMALProcess start, auto delete: false
19:57:20.219 T:1926318592   DEBUG: CMMALRenderer::PreInit
19:57:20.219 T:1353708288   DEBUG: CMMALRenderer::Run - starting
19:57:20.220 T:1362096896   DEBUG: Thread VideoPlayer start, auto delete: false
19:57:20.221 T:1362096896  NOTICE: Creating InputStream
19:57:20.222 T:1362096896   DEBUG: CurlFile::Open(0x512fe610) https://live-vrt.akamaized.net/groupc/live/***replaced***/live_aes.isml/.m3u8
19:57:20.720 T:1926318592   DEBUG: ------ Window Init (DialogBusy.xml) ------
19:57:28.538 T:1370485504   DEBUG: Thread JobWorker 1370485504 terminating (autodelete)
19:57:28.538 T:1404039936   DEBUG: Thread JobWorker 1404039936 terminating (autodelete)
19:57:28.548 T:1412428544   DEBUG: Thread JobWorker 1412428544 terminating (autodelete)
19:57:35.544 T:1362096896  NOTICE: Creating Demuxer
19:57:40.890 T:1362096896    INFO: ffmpeg[512FF300]: [hls,applehttp] Opening 'https://live-vrt.akamaized.net/groupc/live/***replaced***/live_aes.isml/live_aes-audio_t$
19:57:46.274 T:1362096896    INFO: ffmpeg[512FF300]: [hls,applehttp] Opening 'https://live-vrt.akamaized.net/groupc/live/***replaced***/live_aes.isml/live_aes-audio_t$
19:57:51.645 T:1362096896    INFO: ffmpeg[512FF300]: [hls,applehttp] Opening 'https://live-vrt.akamaized.net/groupc/live/***replaced***/live_aes.isml/live_aes-audio_t$
19:57:46.274 T:1362096896    INFO: ffmpeg[512FF300]: [hls,applehttp] Opening 'https://live-vrt.akamaized.net/groupc/live/***replaced***/live_aes.isml/live_aes-audio_t$
19:57:51.645 T:1362096896    INFO: ffmpeg[512FF300]: [hls,applehttp] Opening 'https://live-vrt.akamaized.net/groupc/live/***replaced***/live_aes.isml/live_aes-audio_t$
19:57:57.009 T:1362096896    INFO: ffmpeg[512FF300]: [hls,applehttp] Opening 'https://live-vrt.akamaized.net/groupc/live/***replaced***/live_aes.isml/live_aes-audio_t$
19:58:02.373 T:1362096896    INFO: ffmpeg[512FF300]: [hls,applehttp] Opening 'https://live-vrt.akamaized.net/groupc/live/***replaced***/live_aes.isml/live_aes-audio_t$
19:58:06.095 T:1926318592    INFO: CheckIdle - Closing session to https://live-vrt.akamaized.net (easy=0x6304550, multi=0x5981e430)
19:58:07.445 T:1362096896   DEBUG: Error, could not open file https://live-vrt.akamaized.net/groupc/live/***replaced***/live_aes.isml/.m3u8

```

**Comment by pietje666** [comment]
fixed
