### ISSUE TITLE
Some HLS streams fail with "415 Unsupported Media Type"

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#307]
### Describe the bug ###
There is an outstanding issue at VRT NU where some episodes do not work when using HLS streams (i.e. when not using Widevine). The problem has been reported a few times to VRT and they have confirmed this general issue. In most cases they will fix the faulty stream by hand when reported, but the root cause is yet unknown and unfixed.

### To reproduce ###
1. Disable Widevine (and restart the add-on)
2. Go to program **24 hours in police custody**
3. Click on episode **S04E05**
4. See error **415 Unsupported Media Type**

### Work around ###
Enable Widevine in the settings so the VRT NU add-on selects te MPEG-DASH stream that is unaffected by this issue.

### Additional context ###
- Operating system: LibreELEC 9.0.2
- Kodi version: Leia 18.2
- Addon version: 1.10.0
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
This is an example log from an earlier identical issue.
```paste below
2019-06-14 02:24:56.218 T:1321550704  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/ondemand_vrtPlayerToken.tkn'
2019-06-14 02:24:56.219 T:1321550704  NOTICE: [plugin.video.vrt.nu] URL get: https://media-services-public.vrt.be/vualto-video-aggregator-web/rest/external/v1/videos/pbs-pub-cd09cc3c-5178-49c1-9387-715cb9ad98ff$
vid-d0b7cfaa-fd96-448e-9923-281b10261bfa?vrtPlayerToken=b10@b04c02c93691e93774a02025a289e44ce86e4ef8fc3f9d567d427964d37a1c4c&client=vrtvideo
2019-06-14 02:24:56.466 T:1321550704  NOTICE: [plugin.video.vrt.nu] URL get: https://remix-cf-vrt.akamaized.net/remix/18f7b87b-2715-490c-9ac6-8f05fbf5c7e4/remix_aes.ism/.m3u8?hd
2019-06-14 02:24:56.655 T:1321550704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 415: Unsupported Media Type
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/addon.py", line 13, in <module>
                                                router.router(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/router.py", line 70, in router
                                                _vrtplayer.play(params)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 222, in play
                                                stream = _streamservice.get_stream(params)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/streamservice.py", line 245, in get_stream
                                                stream = StreamURLS(*self._select_hls_substreams(manifest_url))
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/streamservice.py", line 276, in _select_hls_substreams
                                                hls_playlist = urlopen(master_hls_url).read().decode('utf-8')
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 415: Unsupported Media Type
                                            -->End of Python script error report<--
2019-06-14 02:24:56.679 T:1937156496   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vrt.nu/?publication_id=pbs-pub-cd09cc3c-5178-49c1-9387-715cb9ad98ff&action=play&video_id=vi
d-d0b7cfaa-fd96-448e-9923-281b10261bfa&video_url=https%3A%2F%2Fwww.vrt.be%2Fvrtnu%2Fa-z%2Fappel-d-urgence%2F2%2Fappel-d-urgence-s2a1%2F]
```

**Comment by michaelarnauts** [comment]
I saw this also with an episode of Karrewiet. This also occured on the vrt.nu website. I reported this to vrt and they had fixed this.

This might have nothing to do with the add-on...

**Comment by mediaminister** [comment]
Indeed, it doesn't play on  VRT NU website either:
https://www.vrt.be/vrtnu/a-z/appel-d-urgence/2/appel-d-urgence-s2a1/
And this error was reported to VRT NU, but they denied that there was a problem. Unbelievable!
https://twitter.com/bertvandepoel/status/1138232737263960064

**Comment by dagwieers** [comment]
@mediaminister I did try using **inputstream.adaptive** though, but maybe something else was wrong. Will try again later.
*
Should we provide a more sensible error to the user? *E.g. try again with or without inputstream.adaptive, try running it from VRT NU website and report to VRT.*

Thanks everyone.

**Comment by mediaminister** [comment]
Okay, I'll "fix" this providing a message to the user.
And VRT should fix this problem as explained here: https://docs.unified-streaming.com/documentation/vod/troubleshooting.html#unsupported-media-type

**Comment by dagwieers** [comment]
I added a `vrtnu` label so we can also track issues that originate at VRT NU. Personally I am a big fan to also track issues that originate at VRT for the simple reason that we could improve the Kodi plugin (either with a workaround, or with better error messages like we did here).

At some point we will cover most of the common/recurring issues with proper messages so that our users know exactly what to expect (and confidence in our solution stays high despite glitches elsewhere).

**Comment by dagwieers** [comment]
I cannot play the first and second episode using the Kodi plugin now, both with and without inputstream.adaptive. I am using the upcoming v2.0.0 (although I doubt this matters).

**Comment by mediaminister** [comment]
You should have a recent Widevine CDM binary installed. Appel d'urgence is encrypted.
Maybe your Widevine binary is outdated or blacklisted.

**Comment by dagwieers** [comment]
@mediaminister Could be, I noticed that on my other "identical" device it did work today.

**Comment by dagwieers** [comment]
I first removed some files in .kodi/cdm and in .kodi/cdm/widevine, without success. Then I reinstalled Widevine by first removing the library symlink in .kodi/cdm, also without success.

So one of my devices still gets a HTTP 415 error. (Could be that the time of testing makes a difference too ?)

**Comment by mediaminister** [comment]
No, Appel d'urgence should play fine with inputstream.adaptive and DRM.
I tested this in VMWare Player with LibreELEC 9.0.2.
Can you doublecheck if you use the latest inputstream.adaptive version for LibreELEC? You have to install this manually via add-on search.

**Comment by dagwieers** [comment]
It is definitely not the latest inputstream.adaptive because LibreELEC (or the official repositories?) only ship **2.3.17.1** for ARM (while I am waiting for https://github.com/peak3d/inputstream.adaptive/pull/259 to be available).

I would also like to add an About section in the settings that shows different things about the plugin (versions, DRM, Widevine version, etc...) and add some information in the Wiki about what is required for proper playback (a moving target).

**Comment by mediaminister** [comment]
Inputstream Adaptive 2.3.17.1 is the latest version for LibreELEC and in my test Appel d'urgence just plays fine with this version.

If you keep getting http 415 with Appel d'urgence and you're sure you have Inputstream Adaptive 2.3.17.1 and Widevine installed and enabled, there must be something wrong the streamservice stream selection.

Can you please test with other Widevine protected streams? Like Netflix or VTM/Stievie.
Can you provide a debug log?

If we can't find the cause of this problem, we can't add well-directed info about streaming requirements to the wiki.
It's difficult to provide correct information

**Comment by dagwieers** [comment]
Just a few minutes ago I got an **inputstream.adaptive** update to v2.3.22.1 for my Raspberry Pi and everything failed to work (failed differently then before). I then rebooted my system (which I tried before) and then it magically worked. No Widevine was updated.

I also noticed that the DRM option (advertised for 720p live stream support) also affects playback here. Somehow I assumed that it was only required for live stream support, and the VOD content would automatically use DRM if needed.

So to avoid any confusion, I think we ought to change the text for that option to: "Use DRM *(required to play protected content)*"

**Comment by mediaminister** [comment]
The cause was definitely the DRM option, I overlooked that. I improved the stream error message in: https://github.com/pietje666/plugin.video.vrt.nu/pull/332

**Comment by mediaminister** [comment]
All four episodes of Appel d'urgence are affected and VRT didn't fix this yet...

**Comment by mediaminister** [comment]
Okay, VRT fixed it yesterday.

**Comment by dagwieers** [comment]
I reported another issue related to HLS stream playback (episode **S04E05** of **24 hours in police custody**) and VRT confirmed they still have intermittent issues related to this that they are trying to get fixed, so it still may happen from time to time...

**Comment by mediaminister** [comment]
VRT NU uses Unified Origin and HTTP Error 415 is documented, only VRT NU can fix it: https://docs.unified-streaming.com/documentation/vod/index.html

**Comment by dagwieers** [comment]
So we discovered that the VRT Radio2 live stream also suffers from this issue:
https://github.com/pietje666/plugin.video.vrt.nu/pull/685#issuecomment-580710059

**Comment by dagwieers** [comment]
This happened again last night on the latest De Afspraak episode (2020-04-09).
I reported it to VRT NU.

**Comment by mediaminister** [comment]
This time only the MPEG DASH stream failed, HLS was fine.

This means Inputstream Adaptive detects the HTTP 415 error, but as far as I know there is no interface to catch the error in Python and show an error message to the user...

**Comment by dagwieers** [comment]
We cannot easily handle this better. We handed this over to IA and any conceivable way to check playback is worse than the problem IMO.

**Comment by mediaminister** [comment]
If `xbmc.Player.onPlayBackError` could return http errors, then it would be easy to automatically select the HLS stream if MPEG DASH failed.

**Comment by dagwieers** [comment]
Can we make a new ticket for this?

This might also be the right way to handle Widevine issues. There is a missing link there too that we can have add-ons support through inputstreamhelper.
