### ISSUE TITLE
Skipping unplayable item

### ISSUE THREAD

**Issue by BartDelrue** [pietje666/plugin.video.vrt.nu#36]
**Describe the bug**
Video's are unable to play. 
This problem has been occurring for a while now, despite the upgrade to 1.4.2 and a complete reinstall of kodi.

**To Reproduce**
1. try to play any video

**(please complete the following information):**
 - Operating system: Raspbian (jessie)
 - Kodi Version: 17.3

**Additional context**
- Using a VPN: no
- Country you are using the addon from: Belgium

**Log (if available)**
```
16:46:29.600 T:1637872560   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('targetUrls',)
                                            Traceback (most recent call last):
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/addon.py", line 43, in <module>
                                                router(sys.argv[2][1:])
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/addon.py", line 36, in router
                                                vrt_player.play_vrtnu_video(params['video'])
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py", line 79, in play_vrtnu_video
                                                stream = self._url_toStream_service.get_stream_from_url(url)
                                              File "/root/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py", line 75, in get_stream_from_url
                                                hls = self.__get_hls(stream_response.json()['targetUrls'])
                                            KeyError: ('targetUrls',)
                                            -->End of Python script error report<--
16:46:29.642 T:1945694880   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vrt.nu/?action=play&video=%2Fvrtnu%2Fa-z%2Fthuis%2F24%2Fthuis-s24a4477%2F]
```

Your help is much appreciated!

**Comment by pietje666** [comment]
Hi Bart thanks for the report. This bug is related to your vrt nu account. Try logging in on vrt nu using an incognito window. Then vrt nu will ask to accept some extra terms and you will be able to use the addon again. Atleast that is what i have been told by other users who had the same issue. Let me know if it worked out!

**Comment by BartDelrue** [comment]
Thank you!
Works like a charm now.
