### ISSUE TITLE
Plugin crashes since v2.1.0

### ISSUE THREAD

**Issue by yorickps** [pietje666/plugin.video.vrt.nu#396]
### Describe the bug ###

Upon start or autostart, the plugin crashes. 

### To Reproduce ###

1. Start Kodi
2. Open VRTnu plugin
3. Plugin crashes

### Additional context ###

- Operating system: Linux 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux
- Kodi version: 17.6
- Addon version: 2.1.0
- Using a VPN: no
- Country you are using the addon from: BE

### Log (if available) ###

I've got this in the kodi.log

```
20:50:10.220 T:139859986700032   DEBUG: CPythonInvoker(2, /home/yorick/.kodi/addons/plugin.video.vrt.nu/addon.py): entering source directory /home/yorick/.kodi/addons/plugin.video.vrt.nu
20:50:10.220 T:139859986700032   DEBUG: CPythonInvoker(2, /home/yorick/.kodi/addons/plugin.video.vrt.nu/addon.py): instantiating addon using automatically obtained id of "plugin.video.vrt.nu" dependent on version 2.25.0 of the xbmc.python api
20:50:10.344 T:139859986700032   DEBUG: [plugin.video.vrt.nu][routing] Dispatching to 'main_menu', args: {}
20:50:10.641 T:139859986700032   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'offscreen' is an invalid keyword argument for this function
                                            Traceback (most recent call last):
                                              File "/home/yorick/.kodi/addons/plugin.video.vrt.nu/addon.py", line 237, in <module>
                                                plugin.run(sys.argv)
                                              File "/home/yorick/.kodi/addons/script.module.routing/lib/routing.py", line 115, in run
                                                self._dispatch(path)
                                              File "/home/yorick/.kodi/addons/script.module.routing/lib/routing.py", line 126, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/yorick/.kodi/addons/plugin.video.vrt.nu/addon.py", line 26, in main_menu
                                                vrtplayer.VRTPlayer(kodi).show_main_menu_items()
                                              File "/home/yorick/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 75, in show_main_menu_items
                                                self._kodi.show_listing(main_items)
                                              File "/home/yorick/.kodi/addons/plugin.video.vrt.nu/resources/lib/kodiwrapper.py", line 182, in show_listing
                                                list_item = xbmcgui.ListItem(label=title_item.title, offscreen=True)
                                            TypeError: 'offscreen' is an invalid keyword argument for this function
                                            -->End of Python script error report<--
20:50:10.659 T:139862114853632   DEBUG: ------ Window Init (DialogBusy.xml) ------
20:50:10.694 T:139859986700032    INFO: Python script stopped
20:50:10.694 T:139859986700032   DEBUG: Thread LanguageInvoker 139859986700032 terminating
20:50:10.704 T:139862114853632   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/
20:50:10.705 T:139862114853632   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/) failed
20:50:10.705 T:139862114853632   DEBUG: CGUIMediaWindow::GetDirectory ()
20:50:10.705 T:139862114853632   DEBUG:   ParentPath = [plugin://plugin.video.vrt.nu/]
```

**Comment by dagwieers** [comment]
This is unfortunate. I released an emergency fix for this.
You can find it at: https://github.com/pietje666/plugin.video.vrt.nu/releases
