### ISSUE TITLE
Unicode issue in TV Guide

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#405]
### Describe the bug ###
I just encountered another Unicode issue in Today's guide (2019-07-29) for Eén.

### Additional context ###
- Operating system: LibreELEC v9.0.2
- Kodi version: v18.2
- Addon version: v2.1.1
- Using a VPN: no
- Country you are using the addon from: BE

### Log (if available) ###
```paste below
2019-07-29 09:49:45.354 T:1552888688   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/addon.py", line 237, in <module>
                                                plugin.run(sys.argv)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 115, in run
                                                self._dispatch(path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 126, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/addon.py", line 179, in tvguide
                                                tvguide_module.TVGuide(kodi).show_tvguide(date=date, channel=channel)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tvguide.py", line 64, in show_tvguide
                                                episode_items = self.show_episodes(date, channel)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tvguide.py", line 183, in show_episodes
                                                program_title = quote(title.encode('utf-8'), '')
                                              File "/usr/lib/python2.7/urllib.py", line 1296, in quote
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
                                            -->End of Python script error report<--
```

**Comment by dagwieers** [comment]
We probably need some unit-tests for this specific issue (i.e. store an example file with Unicode in every field) so we don't re-introduce this error.

**Comment by dagwieers** [comment]
I can no longer reproduce this on the same device. And I have no clue why it did fail.
Yesterday on the same device the TV Guide for Eén did work, but trying to play an entry would fail immediately.

**Comment by mediaminister** [comment]
This is already fixed in `get_context_menu` function in the new metadata class:
https://github.com/pietje666/plugin.video.vrt.nu/blob/3de98edf44edecb1430d08d03a802dba89dabf01/resources/lib/metadata.py#L78

**Comment by dagwieers** [comment]
I guess the next release will become v2.2.0 with the rework of metadata handling?
But I don't see a good reason to release anytime soon. Maybe target end of August unless we have a good reason to release sooner.
