### ISSUE TITLE
Various known cosmetic issues

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#542]
### Describe the bug ###
Small issues I have noticed since the resumepoints implementation. None of these happen often, or can be easily reproduced:
- After playing videos from "Most recent" it returns with an empty directory
- The current directory listing is not updated after making modifications (i.e. after playing episode in Watch Later, the video stays in the listing, only a refresh makes it disappear)
- The "ongoing" overlay icon, or "watch" overlay icon does not always appear correctly in directory after watching videos
  - This requires Container.Refresh
- After playing videos from "Most recent" it returns with a directory listing showing thumbnails as icons (so Content view "videos")
  - Might be a Kodi issue ? Still happens with Kodi v18.5
- When using the add-on extensively my remote's OK button stops working in the add-on (and in all other add-ons) but not in Kodi itself
  - Seems like a Kodi issue, not sure what it is triggered by, seen on Kodi v18.2 *(did not occur to me recently)*
- ~Endless loop (spinner) after playing a video~ #544 
- ~Container.Refresh may be performed on the wrong container~ #553 
- ~Up Next playing the next episode of the wrong season~ #549 

Most of these issues relate to Container.Refresh and seem to be related to delicate timing issues (i.e. refresh happened before information was ready, or Refresh was run twice in quick succession?)

### Additional context ###
- Operating system: LibreELEC 9.0.2, LibreELEC 9.2 Beta1
- Kodi version: 18.2 / 18.4
- Addon version: 2.3.0 master branch
- Using a VPN: no
- Country you are using the addon from: BE

**Comment by dagwieers** [comment]
It is also possible that since everything now is based on JSONRPC, except Container.Refresh (which is using `executebuiltin()`) or internal events, there is an ordering issue.

**Comment by mediaminister** [comment]
I removed the code related to joining threads, as this can lead to timing issues: https://github.com/pietje666/plugin.video.vrt.nu/pull/544
I tested this and switching between Next Up episodes runs smoother.

**Comment by dagwieers** [comment]
The endless loop (spinner) after playing a video I experienced now twice in two days. When this happens you cannot do anything anymore with the remote. So you have to reboot using Kore, or rebooting on CLI.

The log file contains this:
```
2019-10-24 23:54:08.395 T:1706263408  NOTICE: [plugin.video.vrt.nu] URL post: https://video-user-data.vrt.be/resume_points
2019-10-24 23:54:08.977 T:1706263408  NOTICE: [plugin.video.vrt.nu] Write cache 'resume_points.json'.
2019-10-24 23:54:09.169 T:1706263408  NOTICE: [plugin.video.vrt.nu] Cache 'my-recent-1.json' is fresh, expires in 6 minutes and 17 seconds.
2019-10-24 23:54:09.818 T:1706263408 WARNING: Attempt to use invalid handle 4
2019-10-25 00:03:27.233 T:1551328112 WARNING: Previous line repeats 9 times.
```

**Comment by dagwieers** [comment]
### Container.Refresh may be performed on the wrong container
This only appears to be the case when updating resumepoints, because all other calls to `refresh_container()` are performed from the context menu.

The call to `Container.Refresh` for resumepoints was implemented to ensure the ListItem entries change to the correct icons based on whether it was finished watching or prematurely ended.

**Comment by mediaminister** [comment]
I also got `Attempt to use invalid handle` once before I removed `thread.join()`. I have not tested much since then, but I'll try everything to make Kodi crash.

After forced seeking and fast switching between "Up Next" episodes, Kodi freezed and I got this:

`ERROR: OutputPicture - failed to configure renderer`

**Comment by dagwieers** [comment]
### Up Next playing the next episode of the wrong season
After playing "Universiteit van Vlaanderen " S2019E10 (the latest episode of this season), Up Next automatically played S2018E11.

**Comment by mediaminister** [comment]
Fixed Up Next playing the next episode of the wrong season: https://github.com/pietje666/plugin.video.vrt.nu/pull/549

**Comment by dagwieers** [comment]
@mediaminister It is fine to updated the issue description. I will do it now.

**Comment by dagwieers** [comment]
I just got this error:
```
2019-10-26 18:01:39.488 T:1937076240   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-10-26 18:01:39.645 T:1215292288  NOTICE: [plugin.video.vrt.nu] Got VRT NU Player info: {'position': 10.530000686645508, 'total': 780.00006103515625, 'event': u'playbackstopped'}
2019-10-26 18:01:39.645 T:1215292288  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[videoId]=vid-5d08f592-c621-48dd-9942-0eb9da23f569&size=1
2019-10-26 18:01:39.871 T:1215292288  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn'
2019-10-26 18:01:39.871 T:1215292288  NOTICE: [plugin.video.vrt.nu] URL post: https://video-user-data.vrt.be/resume_points
2019-10-26 18:01:40.198 T:1215292288  NOTICE: [plugin.video.vrt.nu] Write cache 'resume_points.json'.
2019-10-26 18:01:40.373 T:1215292288  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn'
2019-10-26 18:01:40.374 T:1215292288  NOTICE: [plugin.video.vrt.nu] URL post: https://video-user-data.vrt.be/resume_points/contentdamvrt20191010universiteitvanvlaanderen20192020a0009depotwp00160242
2019-10-26 18:01:40.374 T:1215292288  NOTICE: [plugin.video.vrt.nu] URL post data:: {"url": "/vrtnu/a-z/universiteit-van-vlaanderen/2019-2020/universiteit-van-vlaanderen-s2019-2020a9/", "position": 10.530000686645508, "total": 780.00006103515625, "whatsonId": "0", "watchLater": false}
2019-10-26 18:01:40.746 T:1084224384  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/favorites/recent
2019-10-26 18:01:40.783 T:1084224384  NOTICE: [plugin.video.vrt.nu] Cache 'favorites.json' is fresh, expires in 4 minutes and 29 seconds.
2019-10-26 18:01:40.798 T:1084224384  NOTICE: [plugin.video.vrt.nu] Cache 'resume_points.json' is fresh, expires in 5 minutes and 0 seconds.
2019-10-26 18:01:40.816 T:1084224384  NOTICE: [plugin.video.vrt.nu] Cache 'my-recent-1.json' is fresh, expires in 40 minutes and 23 seconds.
2019-10-26 18:01:41.555 T:1215292288  NOTICE: [plugin.video.vrt.nu] Write cache 'resume_points.json'.
2019-10-26 18:01:41.727 T:1215292288  NOTICE: [plugin.video.vrt.nu] Execute: XBMC.Container.Refresh
2019-10-26 18:01:42.501 T:1161810816  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/favorites/recent
2019-10-26 18:01:42.542 T:1161810816  NOTICE: [plugin.video.vrt.nu] Cache 'favorites.json' is fresh, expires in 4 minutes and 27 seconds.
2019-10-26 18:01:42.559 T:1161810816  NOTICE: [plugin.video.vrt.nu] Cache 'resume_points.json' is fresh, expires in 4 minutes and 59 seconds.
2019-10-26 18:01:42.582 T:1161810816  NOTICE: [plugin.video.vrt.nu] Cache 'my-recent-1.json' is fresh, expires in 40 minutes and 21 seconds.
2019-10-26 18:01:43.530 T:1937076240   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/favorites/recent) failed
2019-10-26 18:01:43.559 T:1937076240   ERROR: CGUIMediaWindow::GetDirectory() failed
2019-10-26 18:01:44.089 T:1161810816 WARNING: Attempt to use invalid handle 213
2019-10-26 18:01:55.108 T:1623081856 WARNING: Previous line repeats 1 times.
```
After stopping playing an episode of **Universiteit van Vlaanderen** just after I started it.
Even while Kodi asked to get */favorites/recent* **twice**, it issued an error from `GetDirectory()`.

So I think we are doing something wrong somehow. In this case the UI did not show any error, but I think the `Container.Refresh()` must have failed. This may be the same cause for an empty directory, or issues with the directory.

**Comment by mediaminister** [comment]
> I don't understand why this is now needed, while before resumepoints this worked out-of-the-box IIRC.

I tested this before. Kodi resumepoints only work out-of-the-box if no value is set for the 'resumetime` and `totaltime' Listitem properties (Done in `metadata.py`)
We need a manual container refresh because we already set a 'resumetime` and `totaltime' value for all Listitems and we need to update these values.
Directly updating resumepoints in the Kodi database trough the json rpc interface is a solution, but the interface is currently broken: https://github.com/pietje666/plugin.video.vrt.nu/pull/520#issuecomment-541315829

**Comment by dagwieers** [comment]
So could the solution be to only set resumetime and totaltime when they are (sufficiently) different from what Kodi already knows (so only when it has been set online).

That way we only update it online, but almost never have to add it to the ListItem. And we could then only perform a container refresh when the value was changed online. (we need to retain that information somehow).

**Comment by mediaminister** [comment]
There are use cases where people spend 90% of their VRT NU time on the website or the smartphone app and 10% in the Kodi add-on.

I don't think it's an effective solution to complicate resumepoints logic as it will make maintenance harder and it won't benefit all use cases.

**Comment by dagwieers** [comment]
We just got this error. I hope this log is helpful.
```
2019-10-27 20:39:05.995 T:1049469824  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[videoId]=vid-bd31aca7-8787-4298-98c9-b03e6c0a49da&size=1
2019-10-27 20:39:05.998 T:1091433344  NOTICE: [plugin.video.vrt.nu] Got VRT NU Player info: {'position': 2563.828125, 'total': 3519.320068359375, 'event': u'playbackpaused'}
2019-10-27 20:39:06.096 T:1655407488  NOTICE: Previous line repeats 1 times.
2019-10-27 20:39:06.096 T:1655407488   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'episode' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/playerinfo.py", line 62, in onPlayBackPaused
                                                self._info(dict(position=self._last_pos, total=self._total, event='playbackpaused'))
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 357, in <lambda>
                                                PlayerInfo(info=lambda info: self.handle_info(info, video)).run()
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 365, in handle_info
                                                self.push_position(info, video)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 379, in push_position
                                                uuid = self._resumepoints.assetpath_to_uuid(episode.get('assetPath'))
                                            UnboundLocalError: local variable 'episode' referenced before assignment
                                            -->End of Python script error report<--
2019-10-27 20:39:06.282 T:1049469824   ERROR: Previous line repeats 3 times.
```

**Comment by mediaminister** [comment]
> Previous line repeats 1 times.

This probably means there is still a timing problem with the playerinfo threads. I'll investigate.

**Comment by dagwieers** [comment]
I also get reproducible crashes after watching Burning Man S2019E02 and Up Next is switching to S2019E03. This might be related to the fact I am running LibreELEC 9.2 Beta (9.1.501).

There is nothing special in the normal Kodi log when this happens, but Kodi restarts. When debug logging is enabled in Kodi, I get this at te end before the restart:
```
2019-10-27 23:00:39.408 T:1535624064  NOTICE: [plugin.video.vrt.nu] URL post data:: {"url": "/vrtnu/a-z/burning-man/2019/burning-man-s2019a2-champagne-en-paddo-s/", "position": 641.89105224609375, "total": 643.00006103515625, "watchLater": false}
2019-10-27 23:00:39.486 T:1629807488   DEBUG: [plugin.video.youtube] HTTPServer: Ping |127.0.0.1:50152| |204|
2019-10-27 23:00:39.502 T:1516061568   DEBUG: -->Python Interpreter Initialized<--
2019-10-27 23:00:39.503 T:1516061568   DEBUG: CPythonInvoker(20, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_plugin.py): the source file to load is "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_plugin.py"
2019-10-27 23:00:39.504 T:1516061568   DEBUG: CPythonInvoker(20, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_plugin.py): setting the Python path to /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib:/storage/.kodi/addons/script.module.beautifulsoup4/lib:/storage/.kodi/addons/script.module.dateutil/lib:/storage/.kodi/addons/script.module.inputstreamhelper/lib:/storage/.kodi/addons/script.module.pysocks/lib:/storage/.kodi/addons/script.module.routing/lib:/storage/.kodi/addons/script.module.six/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
2019-10-27 23:00:39.504 T:1516061568   DEBUG: CPythonInvoker(20, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_plugin.py): entering source directory /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib
2019-10-27 23:00:39.504 T:1516061568   DEBUG: CPythonInvoker(20, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_plugin.py): instantiating addon using automatically obtained id of "plugin.video.vrt.nu" dependent on version 2.25.0 of the xbmc.python api
2019-10-27 23:00:39.683 T:1516061568   DEBUG: CAddonSettings[plugin.video.vrt.nu]: loading setting definitions
2019-10-27 23:00:39.683 T:1516061568   DEBUG: CAddonSettings[plugin.video.vrt.nu]: trying to load setting definitions from old format...
2019-10-27 23:00:39.685 T:1516061568   DEBUG: CAddonSettings[plugin.video.vrt.nu]: loading setting values
2019-10-27 23:00:39.686 T:1516061568   DEBUG: CSettingsManager: requested setting (bandwidth) was not found.
2019-10-27 23:00:39.686 T:1516061568   DEBUG: CAddonSettings[plugin.video.vrt.nu]: failed to find definition for setting bandwidth. Creating a setting on-the-fly...
2019-10-27 23:00:39.686 T:1516061568   DEBUG: CSettingsManager: requested setting (usecredentials) was not found.
2019-10-27 23:00:39.686 T:1516061568   DEBUG: CAddonSettings[plugin.video.vrt.nu]: failed to find definition for setting usecredentials. Creating a setting on-the-fly...
2019-10-27 23:00:39.686 T:1516061568   DEBUG: CSettingsManager: requested setting (vrtradio) was not found.
2019-10-27 23:00:39.686 T:1516061568   DEBUG: CAddonSettings[plugin.video.vrt.nu]: failed to find definition for setting vrtradio. Creating a setting on-the-fly...
2019-10-27 23:00:39.794 T:1358386048   DEBUG: onExecutionDone(17, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_plugin.py)
2019-10-27 23:00:40.113 T:1358386048    INFO: Python interpreter stopped
2019-10-27 23:00:40.113 T:1358386048    INFO: Previous line repeats 6 times.
2019-10-27 23:00:40.113 T:1358386048   DEBUG: Thread LanguageInvoker 1358386048 terminating
2019-10-27 23:00:40.114 T:1516061568    INFO: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/programs/burning-man
2019-10-27 23:00:40.116 T:1316422528  NOTICE: [plugin.video.vrt.nu] Protocol: mpeg_dash
2019-10-27 23:00:40.117 T:1516061568   DEBUG: [plugin.video.vrt.nu][routing] Dispatching to 'programs', args: {u'program': u'burning-man'}
2019-10-27 23:00:40.141 T:1274459008   DEBUG: [plugin.video.vrt.nu] Write cache 'resume_points.json'.
2019-10-27 23:00:40.142 T:1516061568   DEBUG: [plugin.video.vrt.nu] Cache 'favorites.json' is fresh, expires in 52 minutes and 6 seconds.
2019-10-27 23:00:40.158 T:1516061568   DEBUG: [plugin.video.vrt.nu] Cache 'resume_points.json' is fresh, expires in 1 hour and 0 minutes.
2019-10-27 23:00:40.297 T:1516061568   DEBUG: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn'
2019-10-27 23:00:40.299 T:1516061568  NOTICE: [plugin.video.vrt.nu] URL post: https://video-user-data.vrt.be/resume_points
2019-10-27 23:00:40.425 T:1316422528    INFO: [plugin.video.vrt.nu] Play: https://ondemand-cf-vrt.akamaized.net/content/vod/vid-55fbaf87-49e3-485a-8f87-6c662ecebce2-CDN_2/vid-55fbaf87-49e3-485a-8f87-6c662ecebce2-CDN_2_nodrm_a5f679b0-d5a3-4103-9423-9ce096b88626.ism/.mpd
2019-10-27 23:00:40.514 T:1274459008  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[programUrl]=//www.vrt.be/vrtnu/a-z/burning-man/&size=300
2019-10-27 23:00:40.657 T:1516061568   DEBUG: [plugin.video.vrt.nu] Write cache 'resume_points.json'.
2019-10-27 23:00:40.864 T:1274459008    INFO: CPythonInvoker(19, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_plugin.py): script successfully run
2019-10-27 23:00:40.864 T:1274459008   DEBUG: onExecutionDone(19, /storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_plugin.py)
2019-10-27 23:00:40.894 T:1937107392   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs/burning-man) failed
2019-10-27 23:00:40.895 T:1937107392   DEBUG: CGUIMediaWindow::GetDirectory ()
2019-10-27 23:00:40.895 T:1937107392   DEBUG:   ParentPath = [plugin://plugin.video.vrt.nu/programs/burning-man]
2019-10-27 23:00:40.953 T:1358386048   DEBUG: Thread BackgroundLoader start, auto delete: false
2019-10-27 23:00:40.963 T:1358386048   DEBUG: Thread BackgroundLoader 1358386048 terminating
2019-10-27 23:00:41.120 T:1274459008    INFO: Python interpreter stopped
2019-10-27 23:00:41.120 T:1274459008   DEBUG: Thread LanguageInvoker 1274459008 terminating
2019-10-27 23:00:41.190 T:1516061568  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[programUrl]=//www.vrt.be/vrtnu/a-z/burning-man/&size=300
```

**Comment by mediaminister** [comment]
I made a new pull request with a different approach regarding the playerinfo threads, that should fix all threading related issues: https://github.com/pietje666/plugin.video.vrt.nu/pull/555

**Comment by dagwieers** [comment]
@mediaminister Weird issue this evening with the master branch. We first watched 2 episodes of Perpetual Grace LTD (E5 and E6) and then I watched De Ideale Wereld (with Jef Neve) and at the end Up Next offered to play Perpetual Grace E7.

No clue how this mix-up could have happened, but I guess we are not sending to Up Next when no next episode is available, and it still somehow had the previous queued/stored.

**Comment by dagwieers** [comment]
Unrelated to the previous report, I noticed that after playing something from "My most recent" and I press the Back button, I end up in the Main menu, not the Favorites menu. I assume this is caused by the Container.Refresh?

**Comment by mediaminister** [comment]
> No clue how this mix-up could have happened, but I guess we are not sending to Up Next when no next episode is available, and it still somehow had the previous queued/stored.

Indeed, we only notify _Up Next add-on_ when an episode starts playing and has a next episode. In this case _Up Next add-on_ was notified to queue Perpetual Grace LTD E7 when Perpetual Grace LTD E6 began playing.

Unfortunately, I can't reproduce this, can you explain in detail how you switched from Perpetual Grace LTD E6 to De Ideale Wereld E19?

**Comment by dagwieers** [comment]
> Unfortunately, I can't reproduce this, can you explain in detail how you switched from Perpetual Grace LTD E6 to De Ideale Wereld E19?

I basically watched PG LTD E5 and E6 in succession, and exited it before Up Next was shown IIRC. Then I started watching DIW E19 and at the end it proposed me to watch PG LTD E7.

I don't think Up Next clears its "next_episode" if Up Next did not initiate the tear-down. So the next media (which did not have a "next_episode" was offered the previous "next_episode".

**Comment by dagwieers** [comment]
> I can't reproduce your issue, I should have more details or a debug log.

That is not what I am saying. If I play something from My recent items, and it has finished. And I press **Back** in the "My recent items" menu, I end up in the Main menu, and not in My favorites menu.

I didn't do any menu manipulations during playback.

**Comment by mediaminister** [comment]
> If I then press Back in the "My recent items" menu, I end up in the "Main" menu, and not in "My favorites" menu as you would expect.

Sorry, I misunderstood. I can reproduce your issue and it's indeed caused by `Container.Refresh`. I'll investigate.

I can't reproduce the "Up Next" issue yet. I'll have to try harder.

**Comment by dagwieers** [comment]
I still would like to avoid those `Container.Refresh` calls, but in case this is not possible, this is just a minor issue to me.

**Comment by mediaminister** [comment]
I think I have a fix: https://github.com/pietje666/plugin.video.vrt.nu/pull/570

**Comment by mediaminister** [comment]
> I don't think Up Next clears its "next_episode" if Up Next did not initiate the tear-down. So the next media (which did not have a "next_episode" was offered the previous "next_episode".

Okay, I can reproduce this by doing the following:
- play an episode that has a next episode
- seek beyond the end time of the episode, so you never see the "Up Next" notification and you trigger `onPlayBackEnded`
- play the last episode of a program, so there is no next episode

**Comment by mediaminister** [comment]
I also could reproduce this bug with the Netflix add-on and I already made a fix: https://github.com/im85288/service.upnext/pull/85

**Comment by dagwieers** [comment]
So, I think we can close this, and when #610 is merged, we should open a new tracking-issue to list and track any issues we find with the current implementation. A stabilization period is needed to ensure we are not introducing regressions.

We should retest all past issues on every fix to ensure we have no regressions.

**Comment by dagwieers** [comment]
I opened #616
