### ISSUE TITLE
categories/programs/A-Z/recent not loading

### ISSUE THREAD

**Issue by svancopp** [pietje666/plugin.video.vrt.nu#682]
### Describe the bug ###
When requesting to list the categories, A-Z or Recent, the script fails to show the listing.

### To Reproduce ###

1. Go to Categories
2. Wait
3. Error is shown

### Additional context ###
character out of range?

Operating system: OSMC
Kodi version: 1.18
Addon version: 2.3.2
Using a VPN: no
Country you are using the addon from: Belgium 🇧🇪

### Log (if available) ###
2020-01-23 22:43:46.508 T:1248846560   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: chr() arg not in range(256)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                run(argv)
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 304, in run
                                                plugin.run(argv)
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 166, in categories
                                                VRTPlayer().show_category_menu(category=category)
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 198, in show_category_menu
                                                category_items = self._apihelper.list_categories()
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 754, in list_categories
                                                categories = get_categories()
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/webscraper.py", line 36, in get_categories
                                                from bs4 import BeautifulSoup, SoupStrainer
                                              File "/home/osmc/.kodi/addons/script.module.beautifulsoup4/lib/bs4/__init__.py", line 36, in <module>
                                                from .builder import builder_registry, ParserRejectedMarkup
                                              File "/home/osmc/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/__init__.py", line 7, in <module>
                                                from bs4.element import (
                                              File "/home/osmc/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py", line 13, in <module>
                                                from bs4.dammit import EntitySubstitution
                                              File "/home/osmc/.kodi/addons/script.module.beautifulsoup4/lib/bs4/dammit.py", line 53, in <module>
                                                class EntitySubstitution(object):
                                              File "/home/osmc/.kodi/addons/script.module.beautifulsoup4/lib/bs4/dammit.py", line 74, in EntitySubstitution
                                                CHARACTER_TO_HTML_ENTITY_RE) = _populate_class_variables()
                                              File "/home/osmc/.kodi/addons/script.module.beautifulsoup4/lib/bs4/dammit.py", line 62, in _populate_class_variables
                                                character = chr(codepoint)
                                            ValueError: chr() arg not in range(256)
                                            -->End of Python script error report<--
2020-01-23 22:43:46.762 T:1400894176   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/categories
2020-01-23 22:43:46.764 T:1915344432   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/categories) failed

**Comment by mediaminister** [comment]
This is not a VRT NU add-on error, but a `beautifulsoup4` error. You should try to uninstall and reinstall beautifulsoup4 on your system.
```
sudo apt-get purge python-bs4
sudo apt-get install python-bs4
```
Manually reinstalling `script.module.beautifulsoup4` (Install from zip file) may also help:
http://mirrors.mit.edu/osmc/osmc/download/kodi/addons/leia/script.module.beautifulsoup4/script.module.beautifulsoup4-4.6.2.zip

**Comment by dagwieers** [comment]
Correct, the **script.module.beautifulsoup4** version we expect to see is **4.6.2** and has this line in the failing codepath:
```python
            character = unichr(codepoint)
```

Kodi should by now be at version **18.5**, you mention 1.18?

Could you please report back so we can get to the bottom of this? Thanks!

**Comment by svancopp** [comment]
You are correct. Rolling back script.module.beautifulsoup4 version to 4.6.2 did the trick. My version was 4.6.3, which seems to be incompatible.

Kodi is indeed 18.5, typo from my part.

Thanks for the quick and helpfull support!

**Comment by mediaminister** [comment]
> My version was 4.6.3, which seems to be incompatible.

beautifulsoup4 has different versions for Python 2 and Python 3.
For Kodi 18 Leia(Python3), you need the Python 2 version: `script.module.beautifulsoup4-4.6.2`
For Kodi 19 Matrix(Python2), which is not yet released, you will need `script.module.beautifulsoup4-4.6.3`

**Comment by svancopp** [comment]
I didn't upgrade the script manually, so I don't know how this version was integrated into my system. Maybe by some other addon?

release notes of the script say nothing has changed :).

= 4.6.3 (20180812)

* Exactly the same as 4.6.2. Re-released to make the README file
  render properly on PyPI.

Anyway, all is working again now.
